<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts"></script>

<template>
  <UApp>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </UApp>
</template>
