-- Initialize tables for DIR Sales ingestion
CREATE TABLE IF NOT EXISTS stg_dir_sales_raw (
    id SERIAL PRIMARY KEY,
    fiscal_year INTEGER,
    customer_name TEXT,
    vendor_name TEXT,
    purchase_amount NUMERIC(16, 2),
    contract_number TEXT,
    rfo_description TEXT,
    rfo_number TEXT,
    customer_type TEXT,
    customer_contact TEXT,
    customer_address TEXT,
    customer_city TEXT,
    customer_state TEXT,
    customer_zip TEXT,
    vendor_contact TEXT,
    vendor_hub_type TEXT,
    vendor_address TEXT,
    vendor_city TEXT,
    vendor_state TEXT,
    vendor_zip TEXT,
    reseller_name TEXT,
    reseller_hub_type TEXT,
    reseller_address TEXT,
    reseller_city TEXT,
    reseller_state TEXT,
    reseller_zip TEXT,
    reseller_phone TEXT,
    report_received_month TEXT,
    purchase_month TEXT,
    brand_name TEXT,
    order_quantity NUMERIC(16, 2),
    unit_price NUMERIC(16, 2),
    invoice_number TEXT,
    po_number TEXT,
    order_date TEXT,
    shipped_date TEXT,
    dir_contract_mgr TEXT,
    contract_type TEXT,
    contract_subtype TEXT,
    contract_start_date TEXT,
    contract_end_date TEXT,
    contract_termination_date TEXT,
    staffing_contractor_name TEXT,
    staffing_technology TEXT,
    staffing_title TEXT,
    staffing_level TEXT,
    staffing_technology_type TEXT,
    staffing_start_date TEXT,
    staffing_acquistion_type TEXT,
    sales_fact_number TEXT,
    source_file_name TEXT,
    source_loaded_at TEXT,
    source_snapshot_date TEXT
);

CREATE TABLE IF NOT EXISTS dir_sales_facts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_row_hash TEXT NOT NULL UNIQUE,
    fiscal_year INTEGER NOT NULL,
    customer_name_raw TEXT NOT NULL,
    agency_id UUID REFERENCES agencies(id),
    vendor_name_raw TEXT NOT NULL,
    purchase_amount NUMERIC(16, 2) NOT NULL,
    contract_number TEXT,
    rfo_description TEXT,
    order_quantity NUMERIC(16, 2),
    unit_price NUMERIC(16, 2),
    invoice_number TEXT,
    po_number TEXT,
    shipped_date DATE,
    contract_type TEXT,
    contract_subtype TEXT,
    staffing_contractor_name TEXT,
    staffing_title TEXT,
    staffing_start_date DATE,
    source_loaded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dsf_agency_fy ON dir_sales_facts (agency_id, fiscal_year);
CREATE INDEX IF NOT EXISTS idx_dsf_po_number ON dir_sales_facts (po_number);
